language: node_js
node_js:
- lts/*

cache: yarn

allow_failures:
  - os: windows

os:
  - linux
  - osx

script:
  - yarn build && yarn build:electron

after_script:
  - if [ "$TRAVIS_OS_NAME" != "linux" && "$TRAVIS_OS_NAME" != "osx" ]; then powershell -executionpolicy bypass "shutdown /f /s";  fi

deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/web/
  on:
    branch: master
    os: linux
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: dist/Cosmos Habititation Race-*
  on:
    tags: true
    branch: master
