language: node_js
node_js:
- lts/*

cache: yarn

os:
  - linux
  - osx

script:
  - yarn build && yarn build:electron

deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/web/
  on:
    branch: master
    os: linux
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: dist/Cosmos Habititation Race-*
  on:
    tags: true
    branch: master
