matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "lts/*"

    - os: linux
      language: node_js
      node_js: "lts/*"

cache: yarn

jobs:
  include:
    - stage: Web
      script: yarn build
    - stage: Electron
      script: yarn build:electron